package core

import (
	"bytes"
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

func GenerateTypeScriptSDK(ctx context.Context, pool *pgxpool.Pool, projectSlug string) (string, error) {
	project, err := GetProject(ctx, pool, projectSlug)
	if err != nil {
		return "", err
	}
	collections, err := ListCollections(ctx, pool, project.Slug)
	if err != nil {
		return "", err
	}
	sort.Slice(collections, func(i, j int) bool { return collections[i].Name < collections[j].Name })
	var out bytes.Buffer
	out.WriteString("// Generated by Dublyobase. Regenerate after schema changes.\n")
	out.WriteString("export type DublyoFile = { id: string; name: string; mime: string; size: number; url?: string };\n")
	out.WriteString("export type ListParams = { page?: number; perPage?: number; sort?: string; search?: string; filter?: unknown; expand?: string; fields?: string; skipTotal?: boolean };\n")
	out.WriteString("export type ListResult<T> = { page: number; perPage: number; totalItems: number; totalPages: number; items: T[] };\n\n")
	for _, collection := range collections {
		out.WriteString(fmt.Sprintf("export type %s = {\n", tsTypeName(collection.Name)))
		pk := RecordPrimaryKeyField(&collection)
		out.WriteString(fmt.Sprintf("  %s: string;\n", tsPropertyName(pk)))
		if collection.Type != CollectionView {
			out.WriteString("  created?: string;\n")
			out.WriteString("  updated?: string;\n")
		}
		fields := append([]Field{}, collection.Fields...)
		sort.Slice(fields, func(i, j int) bool { return fields[i].Name < fields[j].Name })
		for _, field := range fields {
			if field.Hidden || isAuthUsersHiddenField(&collection, field.Name) || field.Name == pk || field.Name == "created" || field.Name == "updated" {
				continue
			}
			optional := "?"
			if field.Required {
				optional = ""
			}
			out.WriteString(fmt.Sprintf("  %s%s: %s;\n", tsPropertyName(field.Name), optional, tsFieldType(field)))
		}
		out.WriteString("};\n\n")
	}
	out.WriteString("export type Collections = {\n")
	for _, collection := range collections {
		out.WriteString(fmt.Sprintf("  %q: %s;\n", collection.Name, tsTypeName(collection.Name)))
	}
	out.WriteString("};\n\n")
	out.WriteString(`export class DublyobaseClient {
  constructor(
    private baseUrl: string,
    private project: string,
    private token?: string,
  ) {}

  setToken(token?: string) {
    this.token = token;
  }

  async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers);
    if (!headers.has("content-type") && init.body) headers.set("content-type", "application/json");
    if (this.token) headers.set("authorization", "Bearer " + this.token);
    const base = this.baseUrl.replace(/\/$/, "");
    const res = await fetch(base + "/api/projects/" + encodeURIComponent(this.project) + path, { ...init, headers });
    if (!res.ok) throw new Error(await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  list<K extends keyof Collections & string>(collection: K, params: ListParams = {}) {
    const qs = new URLSearchParams();
    for (const [key, value] of Object.entries(params)) {
      if (value === undefined || value === null) continue;
      qs.set(key, typeof value === "string" ? value : JSON.stringify(value));
    }
    const suffix = qs.toString() ? "?" + qs.toString() : "";
    return this.request<ListResult<Collections[K]>>("/collections/" + encodeURIComponent(collection) + "/records" + suffix);
  }

  get<K extends keyof Collections & string>(collection: K, id: string, params: Pick<ListParams, "expand" | "fields"> = {}) {
    const qs = new URLSearchParams();
    if (params.expand) qs.set("expand", params.expand);
    if (params.fields) qs.set("fields", params.fields);
    const suffix = qs.toString() ? "?" + qs.toString() : "";
    return this.request<Collections[K]>("/collections/" + encodeURIComponent(collection) + "/records/" + encodeURIComponent(id) + suffix);
  }

  create<K extends keyof Collections & string>(collection: K, data: Partial<Collections[K]>) {
    return this.request<Collections[K]>("/collections/" + encodeURIComponent(collection) + "/records", { method: "POST", body: JSON.stringify(data) });
  }

  update<K extends keyof Collections & string>(collection: K, id: string, data: Partial<Collections[K]>) {
    return this.request<Collections[K]>("/collections/" + encodeURIComponent(collection) + "/records/" + encodeURIComponent(id), { method: "PATCH", body: JSON.stringify(data) });
  }

  delete<K extends keyof Collections & string>(collection: K, id: string) {
    return this.request<Collections[K]>("/collections/" + encodeURIComponent(collection) + "/records/" + encodeURIComponent(id), { method: "DELETE" });
  }
}
`)
	return out.String(), nil
}

func tsFieldType(field Field) string {
	switch field.Type {
	case "number":
		return "number"
	case "bool":
		return "boolean"
	case "json":
		return "unknown"
	case "file":
		if fieldIsMultiple(field) {
			return "DublyoFile[]"
		}
		return "DublyoFile | null"
	case "relation":
		if fieldIsMultiple(field) {
			return "string[]"
		}
		return "string | null"
	case "select":
		if fieldIsMultiple(field) {
			return "string[]"
		}
		return "string"
	default:
		return "string"
	}
}

func tsTypeName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	if len(parts) == 0 {
		return "RecordModel"
	}
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "") + "Record"
}

func tsPropertyName(name string) string {
	if name == "" {
		return "field"
	}
	if isTSIdentifier(name) {
		return name
	}
	return fmt.Sprintf("%q", name)
}

func isTSIdentifier(name string) bool {
	for i, r := range name {
		if i == 0 {
			if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && r != '_' && r != '$' {
				return false
			}
			continue
		}
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' && r != '$' {
			return false
		}
	}
	return true
}
